### PR TITLE
Fix Page overflow should be hidden #2

### LINKED ISSUE #2: Page overflow should be hidden.
The page overflow breaks some styles from the app content. We should let the content be the scrolling container instead of the html page.

image

### PR DESCRIPTION
**Pull request by reachtokish**
Fix #2

### CODE REVIEW

**Comment by jakehamilton** [comment]
Hi @reachtokish, thanks for sending this PR! I may not have done a great job at explaining the expected result in the ticket. I'll try to rephrase it here:

We want only the content below the `AppBar` to scroll. The parent shouldn't scroll at all. That way when we scroll, the `AppBar` remains at the top and we don't accidentally scroll past the `AppContent`.

I don't think we'll need `vh` for this case since sizing is taken care of by the flexbox styles in `App`. Additionally, we only want the page to be able to scroll vertically; horizontal scrolling can be disabled.

**Comment by reachtokish** [comment]
Ok got it. Should I re-try once or you are taking this task?

**Comment by jakehamilton** [comment]
If you want to try fixing it, please do give it a go. I'm happy to have folks contribute to the project. Sometimes we need to tweak things and that's okay!

**Comment by reachtokish** [comment]
I will give a try and will raise a PR

**Comment by jakehamilton** [comment]
Hey @reachtokish, wanted to check in. Are you still planning to work on this?

**Comment by reachtokish** [comment]
Pushed a new fix. Kindly check. Appbar is fixed now on top like what you suggested.

**Comment by reachtokish** [comment]
@jakehamilton does this fix the issue?

**Comment by jakehamilton** [comment]
Hey @reachtokish, sorry for the delay. This gets close to what I'm looking for. I'll close the PR and incorporate these changes in a future commit when I have a moment. Thanks again for helping out!

**Pull request closed without merging**
