### PR TITLE
fix: fixed padding on users list

### LINKED ISSUE #1: Padding missing when user list scrolls.
The padding in the user list is missing at the bottom when content overflows.

image

### PR DESCRIPTION
**Pull request by mstarski**
Ad. #1

### CODE REVIEW

**Comment by jakehamilton** [comment]
Hey @michalStarski, thanks for the contribution! I'll test this out when I have a moment. Is it alright if I assign #1 to you?

**Comment by mstarski** [comment]
@jakehamilton Yup, no problem. Thanks for the fast reply.

**Comment by jakehamilton** [comment]
@michalStarski, I took a look and it seems that names are overflowing:

image

**Comment by mstarski** [comment]
@jakehamilton I guess it should be ok now.

**Comment by jakehamilton** [comment]
Hi @michalStarski, I took a deeper look into the problem and see that it's firefox/edge specific. I've worked around the problem with a similar fix to yours: https://github.com/jakehamilton/scrumfi.sh/pull/9.

I'll mark this PR as accepted and close it since the fix has been implemented. Thanks so much for your help!

**Pull request closed without merging**
